# https://pnpm.io/settings

allowBuilds:
  "@parcel/watcher": true
  babylonjs: false
  core-js: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
  lightningcss: true
  rolldown: true
  unrs-resolver: true
