/**
 * This file is generated from SpikeInterface's "probeinterface_library".
 *
 * It is currently manually updated from the source repo:
 * https://github.com/SpikeInterface/probeinterface_library
 */

// Auto-generated by iterating over every <manufacturer>/<model>/<model>.json file
// in that repo and reading probes[0].annotations.{manufacturer, model_name, description}.
export const KNOWN_PROBES: Record<string, string> = {
  "imec NP1000": "Neuropixels 1.0 probe (NP1000)",
  "imec NP1001": "Neuropixels 1.0 probe with cap (NP1001)",
  "imec NP1010": "Neuropixels 1.0 NHP short staggered probe with cap",
  "imec NP1011":
    "Neuropixels 1.0 NHP short staggered probe with cap, cabling, sharpened",
  "imec NP1012":
    "Neuropixels 1.0 NHP short staggered probe with cap, cabling, sharpened, parylene coating",
  "imec NP1013":
    "Neuropixels 1.0 NHP short staggered probe with cap, cabling, sharpened, parylene coating, sterile packaging",
  "imec NP1014":
    "Neuropixels 1.0 NHP short staggered probe with cap, cabling, sharpened, sterile packaging ",
  "imec NP1015": "Neuropixels 1.0 NHP short linear probe with cap",
  "imec NP1016":
    "Neuropixels 1.0 NHP short linear probe with cap, cabling, sharpened, sterile packaging ",
  "imec NP1017":
    "Neuropixels 1.0 NHP short linear probe with cap, cabling, sharpened, sterile packaging sterilized",
  "imec NP1020": "Npix 1.0 NHP MEDIUM SOI35",
  "imec NP1021": "Npix 1.0 NHP MEDIUM SOI60",
  "imec NP1022": "Neuropixels 1.0 NHP medium linear probe with cap",
  "imec NP1030": "Npix 1.0 NHP LONG SOI90",
  "imec NP1031": "Npix 1.0 NHP LONG SOI125",
  "imec NP1032": "Neuropixels 1.0 NHP long linear probe with cap",
  "imec NP1033":
    "Neuropixels 1.0 NHP long linear probe with cap, cabling, sharpened, sterile packaging ",
  "imec NP1040":
    "Neuropixels 1.0 NHP MAX long, tube underneath shank, linear, probe with silicon cap, 35 um shank thickness",
  "imec NP1041":
    "Neuropixels 1.0 NHP MAX long, tube underneath shank, linear, probe with 1.0 metal cap, 35 um shank thickness",
  "imec NP1042":
    "Neuropixels 1.0 NHP MAX long, tube underneath shank, linear, probe with 2.0 metal cap, 35 um shank thickness",
  "imec NP1050":
    "Neuropixels 1.0 NHP MAX long, tube around shank, linear, probe with 1.0 metal cap",
  "imec NP1051":
    "Neuropixels 1.0 NHP MAX long, tube around shank, linear, probe with 2.0 metal cap",
  "imec NP1100": "Npix 1.0 UHD1 passive",
  "imec NP1120": "Npix 1.0 UHD3 type 1",
  "imec NP1121": "Npix 1.0 UHD3 type 2",
  "imec NP1122": "Npix 1.0 UHD3 type 3",
  "imec NP1123": "Npix 1.0 UHD3 type 4",
  "imec NP1200": "NHP passive probe 25mm, used with 128 ch headstage",
  "imec NP1210": "NHP passive probe 45mm, used with 128 ch headstage",
  "imec NP1300": "Optopix phase1",
  "imec NP2000": "duplicate of PRB2_1_2_0640_0",
  "imec NP2003": "Neuropixels 2.0 single shank probe",
  "imec NP2004": "Neuropixels 2.0 single shank probe with cap",
  "imec NP2005": "Neuropixels 2.0 single shank NHP short linear probe with cap",
  "imec NP2006":
    "Neuropixels 2.0 single shank NHP short staggered probe with cap, cabling, sharpened, sterile packaging ",
  "imec NP2010": "duplicate of PRB2_4_2_0640_0",
  "imec NP2013": "Neuropixels 2.0 multishank probe",
  "imec NP2014": "Neuropixels 2.0 multishank probe with cap",
  "imec NP2020": "Neuropixels 2.0 multi shank probe quad base (Ph 2C)",
  "imec NP2021": "Neuropixels 2.0 multi shank probe quad base with cap (Ph 2C)",
  "imec NP3000": "Neuropixels NXT passive probe",
  "imec NP3010": "Neuropixels NXT phase1B single shank silicon cap",
  "imec NP3011": "Neuropixels NXT phase1B single shank metal cap",
  "imec NP3020": "Neuropixels NXT phase1B multishank silicon cap",
  "imec NP3021": "Neuropixels NXT phase1B multishank metal cap",
  "imec NP3022": "Neuropixels NXT pre-alpha multishank metal cap",
  "imec NP3023": "Neuropixels 3.0 alpha version B multishank silicon cap",
  "imec NP3024": "Neuropixels 3.0 alpha version B multishank metal cap",
  "imec PRB2_1_2_0640_0": "Neuropixels 2.0 phase 1 single shank",
  "imec PRB2_4_2_0640_0": "Neuropixels 2.0 phase 1 multi shank",
  "imec PRB_1_2_0480_2": "Neuropixels 1.0 probe (PRB_1_2_0480_2)",
  "imec PRB_1_4_0480_1": "Neuropixels 1.0 probe (PRB_1_4_0480_1)",
  "imec PRB_1_4_0480_1_C": "Neuropixels 1.0 probe with cap (PRB_1_4_0480_1_C)"
};
