name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: 🟨 Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271
        with:
          version: 11

      - name: 🟩 Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔨 Build app
        run: pnpm build

      - name: 📖 Build docs
        run: pnpm docs:build

      - name: 🔗 Merge docs into app build
        run: cp -r docs/.vitepress/dist dist/spa/docs

      - name: ⬆️ Upload artifact
        if: github.event_name == 'workflow_call'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: "dist/spa"
